[2025-03-19 08:53:47,010] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:03:25,586] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:05:51,235] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:07:47,469] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:09:58,645] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:15:11,227] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:15:41,751] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:17:25,185] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:20:26,322] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:28:15,156] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:30:03,115] ERROR in app: Exception on /registro [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/controlador_usuario.py", line 55, in alta_usuario
    conexion = obtener_conexion()
  File "/app/bd.py", line 5, in obtener_conexion
    return pymysql.connect(host=os.environ.get('DB_HOST'),
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'db' ([Errno -2] Name or service not known)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_usuarios.py", line 49, in registro
    respuesta,code= controlador_usuario.alta_usuario(username,password,perfil,email)
  File "/app/controlador_usuario.py", line 74, in alta_usuario
    except e:
NameError: name 'e' is not defined
[2025-03-19 09:30:03,116] ERROR in app: An exception occurred during a request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/controlador_usuario.py", line 55, in alta_usuario
    conexion = obtener_conexion()
  File "/app/bd.py", line 5, in obtener_conexion
    return pymysql.connect(host=os.environ.get('DB_HOST'),
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'db' ([Errno -2] Name or service not known)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_usuarios.py", line 49, in registro
    respuesta,code= controlador_usuario.alta_usuario(username,password,perfil,email)
  File "/app/controlador_usuario.py", line 74, in alta_usuario
    except e:
NameError: name 'e' is not defined
[2025-03-19 09:30:03,116] INFO in app: path: /registro | method: POST | status: 500 INTERNAL SERVER ERROR | size: 21 >>> 172.19.0.2
[2025-03-19 09:30:03,117] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:30:03] "[35m[1mPOST /registro HTTP/1.1[0m" 500 -
[2025-03-19 09:32:04,244] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:32:22,695] ERROR in app: Exception on /registro [POST]
Traceback (most recent call last):
  File "/app/controlador_usuario.py", line 57, in alta_usuario
    cursor.execute("SELECT perfil FROM usuarios WHERE usuario = %s",(username,))
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'usuario' in 'where clause'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_usuarios.py", line 49, in registro
    respuesta,code= controlador_usuario.alta_usuario(username,password,perfil,email)
  File "/app/controlador_usuario.py", line 74, in alta_usuario
    except e:
NameError: name 'e' is not defined
[2025-03-19 09:32:22,697] ERROR in app: An exception occurred during a request.
Traceback (most recent call last):
  File "/app/controlador_usuario.py", line 57, in alta_usuario
    cursor.execute("SELECT perfil FROM usuarios WHERE usuario = %s",(username,))
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'usuario' in 'where clause'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_usuarios.py", line 49, in registro
    respuesta,code= controlador_usuario.alta_usuario(username,password,perfil,email)
  File "/app/controlador_usuario.py", line 74, in alta_usuario
    except e:
NameError: name 'e' is not defined
[2025-03-19 09:32:22,698] INFO in app: path: /registro | method: POST | status: 500 INTERNAL SERVER ERROR | size: 21 >>> 172.19.0.2
[2025-03-19 09:32:22,699] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:32:22] "[35m[1mPOST /registro HTTP/1.1[0m" 500 -
[2025-03-19 09:35:26,112] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:35:47,226] ERROR in app: Exception on /registro [POST]
Traceback (most recent call last):
  File "/app/controlador_usuario.py", line 61, in alta_usuario
    cursor.execute("INSERT INTO usuarios(nombre,clave,correo,perfil,estado,numeroAccesosErroneo) VALUES(%s,%s,%s,'normal','activo',0)",(username,passwordC,correo))
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'clave' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_usuarios.py", line 49, in registro
    respuesta,code= controlador_usuario.alta_usuario(username,password,perfil,email)
  File "/app/controlador_usuario.py", line 74, in alta_usuario
    except e:
NameError: name 'e' is not defined
[2025-03-19 09:35:47,227] ERROR in app: An exception occurred during a request.
Traceback (most recent call last):
  File "/app/controlador_usuario.py", line 61, in alta_usuario
    cursor.execute("INSERT INTO usuarios(nombre,clave,correo,perfil,estado,numeroAccesosErroneo) VALUES(%s,%s,%s,'normal','activo',0)",(username,passwordC,correo))
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'clave' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_usuarios.py", line 49, in registro
    respuesta,code= controlador_usuario.alta_usuario(username,password,perfil,email)
  File "/app/controlador_usuario.py", line 74, in alta_usuario
    except e:
NameError: name 'e' is not defined
[2025-03-19 09:35:47,227] INFO in app: path: /registro | method: POST | status: 500 INTERNAL SERVER ERROR | size: 21 >>> 172.19.0.3
[2025-03-19 09:35:47,227] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:35:47] "[35m[1mPOST /registro HTTP/1.1[0m" 500 -
[2025-03-19 09:37:26,327] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:37:44,423] INFO in controlador_usuario: Nuevo usuario creado
[2025-03-19 09:37:44,423] INFO in app: path: /registro | method: POST | status: 200 OK | size: 16 >>> 172.19.0.2
[2025-03-19 09:37:44,423] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:37:44] "[37mPOST /registro HTTP/1.1[0m" 200 -
[2025-03-19 09:38:00,160] INFO in controlador_usuario: Acceso usuario fdhsa correcto
[2025-03-19 09:38:00,187] INFO in app: path: /login | method: POST | status: 200 OK | size: 145 >>> 172.19.0.2
[2025-03-19 09:38:00,188] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:38:00] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-19 09:38:00,458] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-19 09:38:00,458] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:38:00] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:38:41,063] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.2
[2025-03-19 09:38:41,064] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:38:41] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-19 09:38:55,885] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-19 09:38:55,886] INFO in app: path: /login | method: POST | status: 200 OK | size: 144 >>> 172.19.0.2
[2025-03-19 09:38:55,886] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:38:55] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-19 09:38:55,941] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-19 09:38:55,941] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:38:55] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:38:59,955] INFO in app: path: /bicis/1 | method: GET | status: 200 OK | size: 138 >>> 172.19.0.2
[2025-03-19 09:38:59,955] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:38:59] "[37mGET /bicis/1 HTTP/1.1[0m" 200 -
[2025-03-19 09:39:03,340] ERROR in app: Exception on /bicis [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 99, in actualizar_bici
    if id.isnumeric() and isinstance(nombre, str) and isinstance(descripcion, str) and precio.isnumeric() and isinstance(foto, str) and len(id)<8 and len(nombre)<128 and len(descripcion)<512 and len(foto)<128 and len(ingredientes)<512:
NameError: name 'ingredientes' is not defined
[2025-03-19 09:39:03,341] ERROR in app: An exception occurred during a request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 99, in actualizar_bici
    if id.isnumeric() and isinstance(nombre, str) and isinstance(descripcion, str) and precio.isnumeric() and isinstance(foto, str) and len(id)<8 and len(nombre)<128 and len(descripcion)<512 and len(foto)<128 and len(ingredientes)<512:
NameError: name 'ingredientes' is not defined
[2025-03-19 09:39:03,341] INFO in app: path: /bicis | method: PUT | status: 500 INTERNAL SERVER ERROR | size: 21 >>> 172.19.0.2
[2025-03-19 09:39:03,342] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:39:03] "[35m[1mPUT /bicis HTTP/1.1[0m" 500 -
[2025-03-19 09:39:13,940] INFO in app: path: /bicis/1 | method: DELETE | status: 200 OK | size: 16 >>> 172.19.0.2
[2025-03-19 09:39:13,940] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:39:13] "[37mDELETE /bicis/1 HTTP/1.1[0m" 200 -
[2025-03-19 09:39:15,038] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 570 >>> 172.19.0.2
[2025-03-19 09:39:15,038] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:39:15] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:39:19,575] INFO in app: path: /bicis/2 | method: GET | status: 200 OK | size: 135 >>> 172.19.0.2
[2025-03-19 09:39:19,575] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:39:19] "[37mGET /bicis/2 HTTP/1.1[0m" 200 -
[2025-03-19 09:39:25,102] ERROR in app: Exception on /bicis [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 99, in actualizar_bici
    if id.isnumeric() and isinstance(nombre, str) and isinstance(descripcion, str) and precio.isnumeric() and isinstance(foto, str) and len(id)<8 and len(nombre)<128 and len(descripcion)<512 and len(foto)<128 and len(ingredientes)<512:
NameError: name 'ingredientes' is not defined
[2025-03-19 09:39:25,102] ERROR in app: An exception occurred during a request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 99, in actualizar_bici
    if id.isnumeric() and isinstance(nombre, str) and isinstance(descripcion, str) and precio.isnumeric() and isinstance(foto, str) and len(id)<8 and len(nombre)<128 and len(descripcion)<512 and len(foto)<128 and len(ingredientes)<512:
NameError: name 'ingredientes' is not defined
[2025-03-19 09:39:25,102] INFO in app: path: /bicis | method: PUT | status: 500 INTERNAL SERVER ERROR | size: 21 >>> 172.19.0.2
[2025-03-19 09:39:25,103] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:39:25] "[35m[1mPUT /bicis HTTP/1.1[0m" 500 -
[2025-03-19 09:39:35,681] ERROR in app: Exception on /bicis [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 99, in actualizar_bici
    if id.isnumeric() and isinstance(nombre, str) and isinstance(descripcion, str) and precio.isnumeric() and isinstance(foto, str) and len(id)<8 and len(nombre)<128 and len(descripcion)<512 and len(foto)<128 and len(ingredientes)<512:
NameError: name 'ingredientes' is not defined
[2025-03-19 09:39:35,681] ERROR in app: An exception occurred during a request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 99, in actualizar_bici
    if id.isnumeric() and isinstance(nombre, str) and isinstance(descripcion, str) and precio.isnumeric() and isinstance(foto, str) and len(id)<8 and len(nombre)<128 and len(descripcion)<512 and len(foto)<128 and len(ingredientes)<512:
NameError: name 'ingredientes' is not defined
[2025-03-19 09:39:35,682] INFO in app: path: /bicis | method: PUT | status: 500 INTERNAL SERVER ERROR | size: 21 >>> 172.19.0.2
[2025-03-19 09:39:35,682] INFO in _internal: 172.19.0.2 - - [19/Mar/2025 09:39:35] "[35m[1mPUT /bicis HTTP/1.1[0m" 500 -
[2025-03-19 09:41:38,159] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:41:52,977] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:41:52,978] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:41:52] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:41:53,745] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:41:53,746] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:41:53] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:41:54,620] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:41:54,620] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:41:54] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:41:56,699] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:41:56,700] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:41:56] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-19 09:42:06,224] INFO in app: path: /login | method: POST | status: 200 OK | size: 55 >>> 172.19.0.3
[2025-03-19 09:42:06,225] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:06] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-19 09:42:12,917] INFO in controlador_usuario: Nuevo usuario creado
[2025-03-19 09:42:12,917] INFO in app: path: /registro | method: POST | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:42:12,917] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:12] "[37mPOST /registro HTTP/1.1[0m" 200 -
[2025-03-19 09:42:19,329] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-19 09:42:19,353] INFO in app: path: /login | method: POST | status: 200 OK | size: 145 >>> 172.19.0.3
[2025-03-19 09:42:19,354] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:19] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-19 09:42:19,397] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:42:19,397] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:19] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:42:38,235] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:42:38,236] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:38] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:42:40,185] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:42:40,186] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:40] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:42:41,939] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:42:41,939] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:41] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-19 09:42:46,769] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-19 09:42:46,770] INFO in app: path: /login | method: POST | status: 200 OK | size: 144 >>> 172.19.0.3
[2025-03-19 09:42:46,770] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:46] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-19 09:42:46,820] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:42:46,820] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:46] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:42:52,802] INFO in app: path: /bicis/2 | method: DELETE | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:42:52,803] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:52] "[37mDELETE /bicis/2 HTTP/1.1[0m" 200 -
[2025-03-19 09:42:54,102] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 573 >>> 172.19.0.3
[2025-03-19 09:42:54,103] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:54] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:42:55,073] INFO in app: path: /bicis/1 | method: GET | status: 200 OK | size: 138 >>> 172.19.0.3
[2025-03-19 09:42:55,073] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:55] "[37mGET /bicis/1 HTTP/1.1[0m" 200 -
[2025-03-19 09:42:58,244] ERROR in app: Exception on /bicis [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 99, in actualizar_bici
    if id.isnumeric() and isinstance(nombre, str) and isinstance(descripcion, str) and precio.isnumeric() and isinstance(foto, str) and len(id)<8 and len(nombre)<128 and len(descripcion)<512 and len(foto)<128 and len(ingredientes)<512:
NameError: name 'ingredientes' is not defined
[2025-03-19 09:42:58,245] ERROR in app: An exception occurred during a request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 99, in actualizar_bici
    if id.isnumeric() and isinstance(nombre, str) and isinstance(descripcion, str) and precio.isnumeric() and isinstance(foto, str) and len(id)<8 and len(nombre)<128 and len(descripcion)<512 and len(foto)<128 and len(ingredientes)<512:
NameError: name 'ingredientes' is not defined
[2025-03-19 09:42:58,246] INFO in app: path: /bicis | method: PUT | status: 500 INTERNAL SERVER ERROR | size: 21 >>> 172.19.0.3
[2025-03-19 09:42:58,246] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:42:58] "[35m[1mPUT /bicis HTTP/1.1[0m" 500 -
[2025-03-19 09:44:37,360] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:45:02,192] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:45:02,193] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:02] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:45:03,033] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:45:03,033] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:03] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-19 09:45:12,868] INFO in controlador_usuario: Nuevo usuario creado
[2025-03-19 09:45:12,869] INFO in app: path: /registro | method: POST | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:45:12,869] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:12] "[37mPOST /registro HTTP/1.1[0m" 200 -
[2025-03-19 09:45:38,166] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-19 09:45:38,204] INFO in app: path: /login | method: POST | status: 200 OK | size: 144 >>> 172.19.0.3
[2025-03-19 09:45:38,204] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:38] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-19 09:45:38,263] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:45:38,263] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:38] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:45:45,098] INFO in app: path: /bicis/2 | method: DELETE | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:45:45,099] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:45] "[37mDELETE /bicis/2 HTTP/1.1[0m" 200 -
[2025-03-19 09:45:46,234] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 573 >>> 172.19.0.3
[2025-03-19 09:45:46,235] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:46] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:45:49,604] INFO in app: path: /bicis/1 | method: GET | status: 200 OK | size: 138 >>> 172.19.0.3
[2025-03-19 09:45:49,605] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:49] "[37mGET /bicis/1 HTTP/1.1[0m" 200 -
[2025-03-19 09:45:52,851] INFO in app: path: /bicis | method: PUT | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:45:52,852] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:52] "[37mPUT /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:45:58,481] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 574 >>> 172.19.0.3
[2025-03-19 09:45:58,482] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:45:58] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:46:35,980] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 09:46:35,980] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:46:35] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 09:46:39,418] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 09:46:39,418] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:46:39] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 09:49:47,096] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 09:50:30,200] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 09:50:30,201] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:50:30] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 09:51:35,480] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 09:51:35,481] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:51:35] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 09:51:39,445] INFO in app: path: /ver/ | method: GET | status: 404 NOT FOUND | size: 232 >>> 172.19.0.3
[2025-03-19 09:51:39,445] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:51:39] "[33mGET /ver/ HTTP/1.1[0m" 404 -
[2025-03-19 09:53:47,619] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 09:53:47,619] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:53:47] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 09:54:05,272] INFO in controlador_usuario: Nuevo usuario creado
[2025-03-19 09:54:05,272] INFO in app: path: /registro | method: POST | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-19 09:54:05,273] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:54:05] "[37mPOST /registro HTTP/1.1[0m" 200 -
[2025-03-19 09:54:10,937] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-19 09:54:10,966] INFO in app: path: /login | method: POST | status: 200 OK | size: 145 >>> 172.19.0.3
[2025-03-19 09:54:10,967] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:54:10] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-19 09:54:11,021] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-19 09:54:11,022] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:54:11] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-19 09:54:21,988] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 09:54:21,989] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 09:54:21] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 10:04:25,769] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-19 10:04:40,214] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 10:04:40,214] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 10:04:40] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 10:04:42,539] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 10:04:42,539] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 10:04:42] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 10:04:51,114] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 10:04:51,115] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 10:04:51] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-19 10:05:00,284] INFO in app: path: /upload | method: POST | status: 400 BAD REQUEST | size: 142 >>> 172.19.0.3
[2025-03-19 10:05:00,284] INFO in _internal: 172.19.0.3 - - [19/Mar/2025 10:05:00] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
[2025-03-20 09:24:18,866] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-20 09:25:43,014] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-20 09:26:42,301] INFO in app: path: /login | method: POST | status: 200 OK | size: 55 >>> 172.19.0.2
[2025-03-20 09:26:42,302] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:26:42] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:26:55,244] INFO in controlador_usuario: Nuevo usuario creado
[2025-03-20 09:26:55,245] INFO in app: path: /registro | method: POST | status: 200 OK | size: 16 >>> 172.19.0.2
[2025-03-20 09:26:55,245] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:26:55] "[37mPOST /registro HTTP/1.1[0m" 200 -
[2025-03-20 09:27:05,122] INFO in controlador_usuario: Acceso usuario ivan incorrecto
[2025-03-20 09:27:05,157] INFO in app: path: /login | method: POST | status: 200 OK | size: 55 >>> 172.19.0.2
[2025-03-20 09:27:05,157] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:05] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:27:09,942] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-20 09:27:09,975] INFO in app: path: /login | method: POST | status: 200 OK | size: 145 >>> 172.19.0.2
[2025-03-20 09:27:09,976] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:09] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:27:10,052] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:10,053] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:10] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:13,763] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:13,764] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:13] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:15,286] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:15,286] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:15] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:15,826] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:15,826] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:15] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:16,577] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:16,577] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:16] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:17,184] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:17,184] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:17] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:17,792] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:17,793] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:17] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:18,502] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:18,502] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:18] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:18,797] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:18,797] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:18] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:19,003] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:19,004] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:19] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:19,482] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:19,482] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:19] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:20,153] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:20,153] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:20] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:23,736] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:23,737] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:23] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:24,444] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:24,444] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:24] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:24,627] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:24,628] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:24] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:25,076] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:25,077] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:25] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:25,525] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:25,525] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:25] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:26,020] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:26,020] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:26] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:43,898] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:43,899] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:43] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:44,455] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:44,456] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:44] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:27:44,990] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:27:44,991] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:27:44] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:28:15,902] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:28:15,902] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:28:15] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:28:36,763] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:28:36,764] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:28:36] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:28:37,435] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:28:37,435] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:28:37] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:28:48,222] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:28:48,222] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:28:48] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:28:48,694] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:28:48,695] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:28:48] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:28:56,473] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:28:56,474] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:28:56] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:30:06,405] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:30:06,406] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:30:06] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:30:12,916] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:30:12,916] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:30:12] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:31:15,005] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:31:15,006] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:31:15] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:31:16,187] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:31:16,187] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:31:16] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:31:17,671] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.2
[2025-03-20 09:31:17,672] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:31:17] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-20 09:31:22,587] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-20 09:31:22,587] INFO in app: path: /login | method: POST | status: 200 OK | size: 144 >>> 172.19.0.2
[2025-03-20 09:31:22,588] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:31:22] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:31:22,644] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:31:22,644] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:31:22] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:38:55,559] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-20 09:39:23,152] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:39:23,152] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:23] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:39:24,012] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.2
[2025-03-20 09:39:24,013] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:24] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-20 09:39:28,671] INFO in app: path: /login | method: POST | status: 200 OK | size: 55 >>> 172.19.0.2
[2025-03-20 09:39:28,671] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:28] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:39:36,179] INFO in controlador_usuario: Nuevo usuario creado
[2025-03-20 09:39:36,179] INFO in app: path: /registro | method: POST | status: 200 OK | size: 16 >>> 172.19.0.2
[2025-03-20 09:39:36,179] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:36] "[37mPOST /registro HTTP/1.1[0m" 200 -
[2025-03-20 09:39:42,580] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-20 09:39:42,615] INFO in app: path: /login | method: POST | status: 200 OK | size: 145 >>> 172.19.0.2
[2025-03-20 09:39:42,616] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:42] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:39:42,682] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:39:42,683] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:42] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:39:43,712] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:39:43,712] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:43] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:39:45,709] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:39:45,710] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:45] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:39:46,511] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:39:46,511] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:39:46] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:40:03,197] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.2
[2025-03-20 09:40:03,197] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:40:03] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-20 09:40:08,491] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-20 09:40:08,491] INFO in app: path: /login | method: POST | status: 200 OK | size: 144 >>> 172.19.0.2
[2025-03-20 09:40:08,492] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:40:08] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:40:08,550] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.2
[2025-03-20 09:40:08,550] INFO in _internal: 172.19.0.2 - - [20/Mar/2025 09:40:08] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:41:44,700] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-20 09:42:33,125] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-20 09:42:33,126] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:42:33] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:42:33,819] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-20 09:42:33,819] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:42:33] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-20 09:42:43,368] INFO in app: path: /registro | method: POST | status: 200 OK | size: 51 >>> 172.19.0.3
[2025-03-20 09:42:43,369] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:42:43] "[37mPOST /registro HTTP/1.1[0m" 200 -
[2025-03-20 09:42:53,899] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-20 09:42:53,900] INFO in app: path: /login | method: POST | status: 200 OK | size: 144 >>> 172.19.0.3
[2025-03-20 09:42:53,900] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:42:53] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:42:53,955] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-20 09:42:53,956] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:42:53] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:43:00,195] ERROR in app: Exception on /bicis [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 53, in guardar_bici
    respuesta,code=controlador_bicis.insertar_bici(nombre,descripcion,precio,foto)
AttributeError: module 'controlador_bicis' has no attribute 'insertar_bici'
[2025-03-20 09:43:00,195] ERROR in app: An exception occurred during a request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/rutas_bicis.py", line 53, in guardar_bici
    respuesta,code=controlador_bicis.insertar_bici(nombre,descripcion,precio,foto)
AttributeError: module 'controlador_bicis' has no attribute 'insertar_bici'
[2025-03-20 09:43:00,195] INFO in app: path: /bicis | method: POST | status: 500 INTERNAL SERVER ERROR | size: 21 >>> 172.19.0.3
[2025-03-20 09:43:00,196] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:43:00] "[35m[1mPOST /bicis HTTP/1.1[0m" 500 -
[2025-03-20 09:44:55,759] INFO in _internal:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2025-03-20 09:45:04,201] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-20 09:45:04,201] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:04] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:45:05,087] INFO in app: path: /logout | method: GET | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-20 09:45:05,088] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:05] "[37mGET /logout HTTP/1.1[0m" 200 -
[2025-03-20 09:45:09,706] INFO in controlador_usuario: Acceso usuario ivan correcto
[2025-03-20 09:45:09,707] INFO in app: path: /login | method: POST | status: 200 OK | size: 144 >>> 172.19.0.3
[2025-03-20 09:45:09,707] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:09] "[37mPOST /login HTTP/1.1[0m" 200 -
[2025-03-20 09:45:09,773] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-20 09:45:09,773] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:09] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:45:15,263] INFO in app: path: /bicis | method: POST | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-20 09:45:15,263] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:15] "[37mPOST /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:45:16,464] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 794 >>> 172.19.0.3
[2025-03-20 09:45:16,464] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:16] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:45:21,907] INFO in app: path: /bicis/6 | method: DELETE | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-20 09:45:21,908] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:21] "[37mDELETE /bicis/6 HTTP/1.1[0m" 200 -
[2025-03-20 09:45:23,118] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 710 >>> 172.19.0.3
[2025-03-20 09:45:23,118] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:23] "[37mGET /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:45:26,042] INFO in app: path: /bicis/1 | method: GET | status: 200 OK | size: 138 >>> 172.19.0.3
[2025-03-20 09:45:26,043] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:26] "[37mGET /bicis/1 HTTP/1.1[0m" 200 -
[2025-03-20 09:45:28,443] INFO in app: path: /bicis | method: PUT | status: 200 OK | size: 16 >>> 172.19.0.3
[2025-03-20 09:45:28,444] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:28] "[37mPUT /bicis HTTP/1.1[0m" 200 -
[2025-03-20 09:45:31,306] INFO in app: path: /bicis | method: GET | status: 200 OK | size: 715 >>> 172.19.0.3
[2025-03-20 09:45:31,307] INFO in _internal: 172.19.0.3 - - [20/Mar/2025 09:45:31] "[37mGET /bicis HTTP/1.1[0m" 200 -
